## Pandas

Pandas is a library which is used for data manipulation and data processing

Work with structured data (rows & columns)
Read/write data (CSV, Excel, JSON, etc.)
Data cleaning & preprocessing
Fast operations on large datasets

## Dataframe

Dataframe is used for reading a data which is in dictionary or json or any format and representing into a table format or structured format

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Col1','Col2','Col3','Col4'])

In [6]:
df.head() # head shows only first 5 rows

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [7]:
df.to_csv('Test.csv')

In [9]:
# Accessing the element in dataframe

df.loc["Row1"]

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

## Dataseries

A Data Series in Pandas is a one-dimensional labeled array

In [11]:
type(df.loc['Row1'])

pandas.core.series.Series

In [12]:
# iloc is used for accessing the element from the dataframe using index

df.iloc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [15]:
df.iloc[:,3:] # to access the column 4

      Col4
Row1     3
Row2     7
Row3    11
Row4    15
Row5    19

In [17]:
df.iloc[:,3:].values # to convert the dataframe into array

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [18]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
df.sum()

Col1    40
Col2    45
Col3    50
Col4    55
dtype: int64

In [24]:
df.isnull().sum() # this will check if any column contains missing values

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [26]:
df['Col1'].value_counts() # this will store a count of the unique elements occuring in Col1

Col1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [9]:
df=pd.read_csv('mercedesbenz.csv') # reading the csv and showing in table format

In [7]:
df.shape

(4209, 378)

In [8]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [11]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [13]:
df[df['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

 ## Reading JSON

In [16]:
from io import StringIO

In [14]:
Data='{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'

In [17]:
pd.read_json(StringIO(Data))

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [18]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')

In [19]:
df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [21]:
df.to_csv('wine.csv') # converts json to csv

In [23]:
df.to_json(orient='records') # converts csv to json

'[{"1":1,"14.23":13.2,"1.71":1.78,"2.43":2.14,"15.6":11.2,"127":100,"2.8":2.65,"3.06":2.76,".28":0.26,"2.29":1.28,"5.64":4.38,"1.04":1.05,"3.92":3.4,"1065":1050},{"1":1,"14.23":13.16,"1.71":2.36,"2.43":2.67,"15.6":18.6,"127":101,"2.8":2.8,"3.06":3.24,".28":0.3,"2.29":2.81,"5.64":5.68,"1.04":1.03,"3.92":3.17,"1065":1185},{"1":1,"14.23":14.37,"1.71":1.95,"2.43":2.5,"15.6":16.8,"127":113,"2.8":3.85,"3.06":3.49,".28":0.24,"2.29":2.18,"5.64":7.8,"1.04":0.86,"3.92":3.45,"1065":1480},{"1":1,"14.23":13.24,"1.71":2.59,"2.43":2.87,"15.6":21.0,"127":118,"2.8":2.8,"3.06":2.69,".28":0.39,"2.29":1.82,"5.64":4.32,"1.04":1.04,"3.92":2.93,"1065":735},{"1":1,"14.23":14.2,"1.71":1.76,"2.43":2.45,"15.6":15.2,"127":112,"2.8":3.27,"3.06":3.39,".28":0.34,"2.29":1.97,"5.64":6.75,"1.04":1.05,"3.92":2.85,"1065":1450},{"1":1,"14.23":14.39,"1.71":1.87,"2.43":2.45,"15.6":14.6,"127":96,"2.8":2.5,"3.06":2.52,".28":0.3,"2.29":1.98,"5.64":5.25,"1.04":1.02,"3.92":3.58,"1065":1290},{"1":1,"14.23":14.06,"1.71":2.15,"2.43":2.61,"15.6":17.6,"127":121,"2.8":2.6,"3.06":2.51,".28":0.31,"2.29":1.25,"5.64":5.05,"1.04":1.06,"3.92":3.58,"1065":1295},{"1":1,"14.23":14.83,"1.71":1.64,"2.43":2.17,"15.6":14.0,"127":97,"2.8":2.8,"3.06":2.98,".28":0.29,"2.29":1.98,"5.64":5.2,"1.04":1.08,"3.92":2.85,"1065":1045},{"1":1,"14.23":13.86,"1.71":1.35,"2.43":2.27,"15.6":16.0,"127":98,"2.8":2.98,"3.06":3.15,".28":0.22,"2.29":1.85,"5.64":7.22,"1.04":1.01,"3.92":3.55,"1065":1045},{"1":1,"14.23":14.1,"1.71":2.16,"2.43":2.3,"15.6":18.0,"127":105,"2.8":2.95,"3.06":3.32,".28":0.22,"2.29":2.38,"5.64":5.75,"1.04":1.25,"3.92":3.17,"1065":1510},{"1":1,"14.23":14.12,"1.71":1.48,"2.43":2.32,"15.6":16.8,"127":95,"2.8":2.2,"3.06":2.43,".28":0.26,"2.29":1.57,"5.64":5.0,"1.04":1.17,"3.92":2.82,"1065":1280},{"1":1,"14.23":13.75,"1.71":1.73,"2.43":2.41,"15.6":16.0,"127":89,"2.8":2.6,"3.06":2.76,".28":0.29,"2.29":1.81,"5.64":5.6,"1.04":1.15,"3.92":2.9,"1065":1320},{"1":1,"14.23":14.75,"1.71":1.73,"2.43":2.39,"15.6":11.4,"127":91,"2.8":3.1,"3.06":3.69,".28":0.43,"2.29":2.81,"5.64":5.4,"1.04":1.25,"3.92":2.73,"1065":1150},{"1":1,"14.23":14.38,"1.71":1.87,"2.43":2.38,"15.6":12.0,"127":102,"2.8":3.3,"3.06":3.64,".28":0.29,"2.29":2.96,"5.64":7.5,"1.04":1.2,"3.92":3.0,"1065":1547},{"1":1,"14.23":13.63,"1.71":1.81,"2.43":2.7,"15.6":17.2,"127":112,"2.8":2.85,"3.06":2.91,".28":0.3,"2.29":1.46,"5.64":7.3,"1.04":1.28,"3.92":2.88,"1065":1310},{"1":1,"14.23":14.3,"1.71":1.92,"2.43":2.72,"15.6":20.0,"127":120,"2.8":2.8,"3.06":3.14,".28":0.33,"2.29":1.97,"5.64":6.2,"1.04":1.07,"3.92":2.65,"1065":1280},{"1":1,"14.23":13.83,"1.71":1.57,"2.43":2.62,"15.6":20.0,"127":115,"2.8":2.95,"3.06":3.4,".28":0.4,"2.29":1.72,"5.64":6.6,"1.04":1.13,"3.92":2.57,"1065":1130},{"1":1,"14.23":14.19,"1.71":1.59,"2.43":2.48,"15.6":16.5,"127":108,"2.8":3.3,"3.06":3.93,".28":0.32,"2.29":1.86,"5.64":8.7,"1.04":1.23,"3.92":2.82,"1065":1680},{"1":1,"14.23":13.64,"1.71":3.1,"2.43":2.56,"15.6":15.2,"127":116,"2.8":2.7,"3.06":3.03,".28":0.17,"2.29":1.66,"5.64":5.1,"1.04":0.96,"3.92":3.36,"1065":845},{"1":1,"14.23":14.06,"1.71":1.63,"2.43":2.28,"15.6":16.0,"127":126,"2.8":3.0,"3.06":3.17,".28":0.24,"2.29":2.1,"5.64":5.65,"1.04":1.09,"3.92":3.71,"1065":780},{"1":1,"14.23":12.93,"1.71":3.8,"2.43":2.65,"15.6":18.6,"127":102,"2.8":2.41,"3.06":2.41,".28":0.25,"2.29":1.98,"5.64":4.5,"1.04":1.03,"3.92":3.52,"1065":770},{"1":1,"14.23":13.71,"1.71":1.86,"2.43":2.36,"15.6":16.6,"127":101,"2.8":2.61,"3.06":2.88,".28":0.27,"2.29":1.69,"5.64":3.8,"1.04":1.11,"3.92":4.0,"1065":1035},{"1":1,"14.23":12.85,"1.71":1.6,"2.43":2.52,"15.6":17.8,"127":95,"2.8":2.48,"3.06":2.37,".28":0.26,"2.29":1.46,"5.64":3.93,"1.04":1.09,"3.92":3.63,"1065":1015},{"1":1,"14.23":13.5,"1.71":1.81,"2.43":2.61,"15.6":20.0,"127":96,"2.8":2.53,"3.06":2.61,".28":0.28,"2.29":1.66,"5.64":3.52,"1.04":1.12,"3.92":3.82,"1065":845},{"1":1,"14.23":13.05,"1.71":2.05,"2.43":3.22,"15.6":25.0,"127":124,"2.8":2.63,"3.06":2.68,".28":0.47,"2.29":1.92,"5.64":3.58,"1.04":1.13,"3.92":3.2,"1065":830},{"1":1,"14.23":13.39,"1.71":1.77,"2.43":2.62,"15.6":16.1,"127":93,"2.8":2.85,"3.06":2.94,".28":0.34,"2.29":1.45,"5.64":4.8,"1.04":0.92,"3.92":3.22,"1065":1195},{"1":1,"14.23":13.3,"1.71":1.72,"2.43":2.14,"15.6":17.0,"127":94,"2.8":2.4,"3.06":2.19,".28":0.27,"2.29":1.35,"5.64":3.95,"1.04":1.02,"3.92":2.77,"1065":1285},{"1":1,"14.23":13.87,"1.71":1.9,"2.43":2.8,"15.6":19.4,"127":107,"2.8":2.95,"3.06":2.97,".28":0.37,"2.29":1.76,"5.64":4.5,"1.04":1.25,"3.92":3.4,"1065":915},{"1":1,"14.23":14.02,"1.71":1.68,"2.43":2.21,"15.6":16.0,"127":96,"2.8":2.65,"3.06":2.33,".28":0.26,"2.29":1.98,"5.64":4.7,"1.04":1.04,"3.92":3.59,"1065":1035},{"1":1,"14.23":13.73,"1.71":1.5,"2.43":2.7,"15.6":22.5,"127":101,"2.8":3.0,"3.06":3.25,".28":0.29,"2.29":2.38,"5.64":5.7,"1.04":1.19,"3.92":2.71,"1065":1285},{"1":1,"14.23":13.58,"1.71":1.66,"2.43":2.36,"15.6":19.1,"127":106,"2.8":2.86,"3.06":3.19,".28":0.22,"2.29":1.95,"5.64":6.9,"1.04":1.09,"3.92":2.88,"1065":1515},{"1":1,"14.23":13.68,"1.71":1.83,"2.43":2.36,"15.6":17.2,"127":104,"2.8":2.42,"3.06":2.69,".28":0.42,"2.29":1.97,"5.64":3.84,"1.04":1.23,"3.92":2.87,"1065":990},{"1":1,"14.23":13.76,"1.71":1.53,"2.43":2.7,"15.6":19.5,"127":132,"2.8":2.95,"3.06":2.74,".28":0.5,"2.29":1.35,"5.64":5.4,"1.04":1.25,"3.92":3.0,"1065":1235},{"1":1,"14.23":13.51,"1.71":1.8,"2.43":2.65,"15.6":19.0,"127":110,"2.8":2.35,"3.06":2.53,".28":0.29,"2.29":1.54,"5.64":4.2,"1.04":1.1,"3.92":2.87,"1065":1095},{"1":1,"14.23":13.48,"1.71":1.81,"2.43":2.41,"15.6":20.5,"127":100,"2.8":2.7,"3.06":2.98,".28":0.26,"2.29":1.86,"5.64":5.1,"1.04":1.04,"3.92":3.47,"1065":920},{"1":1,"14.23":13.28,"1.71":1.64,"2.43":2.84,"15.6":15.5,"127":110,"2.8":2.6,"3.06":2.68,".28":0.34,"2.29":1.36,"5.64":4.6,"1.04":1.09,"3.92":2.78,"1065":880},{"1":1,"14.23":13.05,"1.71":1.65,"2.43":2.55,"15.6":18.0,"127":98,"2.8":2.45,"3.06":2.43,".28":0.29,"2.29":1.44,"5.64":4.25,"1.04":1.12,"3.92":2.51,"1065":1105},{"1":1,"14.23":13.07,"1.71":1.5,"2.43":2.1,"15.6":15.5,"127":98,"2.8":2.4,"3.06":2.64,".28":0.28,"2.29":1.37,"5.64":3.7,"1.04":1.18,"3.92":2.69,"1065":1020},{"1":1,"14.23":14.22,"1.71":3.99,"2.43":2.51,"15.6":13.2,"127":128,"2.8":3.0,"3.06":3.04,".28":0.2,"2.29":2.08,"5.64":5.1,"1.04":0.89,"3.92":3.53,"1065":760},{"1":1,"14.23":13.56,"1.71":1.71,"2.43":2.31,"15.6":16.2,"127":117,"2.8":3.15,"3.06":3.29,".28":0.34,"2.29":2.34,"5.64":6.13,"1.04":0.95,"3.92":3.38,"1065":795},{"1":1,"14.23":13.41,"1.71":3.84,"2.43":2.12,"15.6":18.8,"127":90,"2.8":2.45,"3.06":2.68,".28":0.27,"2.29":1.48,"5.64":4.28,"1.04":0.91,"3.92":3.0,"1065":1035},{"1":1,"14.23":13.88,"1.71":1.89,"2.43":2.59,"15.6":15.0,"127":101,"2.8":3.25,"3.06":3.56,".28":0.17,"2.29":1.7,"5.64":5.43,"1.04":0.88,"3.92":3.56,"1065":1095},{"1":1,"14.23":13.24,"1.71":3.98,"2.43":2.29,"15.6":17.5,"127":103,"2.8":2.64,"3.06":2.63,".28":0.32,"2.29":1.66,"5.64":4.36,"1.04":0.82,"3.92":3.0,"1065":680},{"1":1,"14.23":13.05,"1.71":1.77,"2.43":2.1,"15.6":17.0,"127":107,"2.8":3.0,"3.06":3.0,".28":0.28,"2.29":2.03,"5.64":5.04,"1.04":0.88,"3.92":3.35,"1065":885},{"1":1,"14.23":14.21,"1.71":4.04,"2.43":2.44,"15.6":18.9,"127":111,"2.8":2.85,"3.06":2.65,".28":0.3,"2.29":1.25,"5.64":5.24,"1.04":0.87,"3.92":3.33,"1065":1080},{"1":1,"14.23":14.38,"1.71":3.59,"2.43":2.28,"15.6":16.0,"127":102,"2.8":3.25,"3.06":3.17,".28":0.27,"2.29":2.19,"5.64":4.9,"1.04":1.04,"3.92":3.44,"1065":1065},{"1":1,"14.23":13.9,"1.71":1.68,"2.43":2.12,"15.6":16.0,"127":101,"2.8":3.1,"3.06":3.39,".28":0.21,"2.29":2.14,"5.64":6.1,"1.04":0.91,"3.92":3.33,"1065":985},{"1":1,"14.23":14.1,"1.71":2.02,"2.43":2.4,"15.6":18.8,"127":103,"2.8":2.75,"3.06":2.92,".28":0.32,"2.29":2.38,"5.64":6.2,"1.04":1.07,"3.92":2.75,"1065":1060},{"1":1,"14.23":13.94,"1.71":1.73,"2.43":2.27,"15.6":17.4,"127":108,"2.8":2.88,"3.06":3.54,".28":0.32,"2.29":2.08,"5.64":8.9,"1.04":1.12,"3.92":3.1,"1065":1260},{"1":1,"14.23":13.05,"1.71":1.73,"2.43":2.04,"15.6":12.4,"127":92,"2.8":2.72,"3.06":3.27,".28":0.17,"2.29":2.91,"5.64":7.2,"1.04":1.12,"3.92":2.91,"1065":1150},{"1":1,"14.23":13.83,"1.71":1.65,"2.43":2.6,"15.6":17.2,"127":94,"2.8":2.45,"3.06":2.99,".28":0.22,"2.29":2.29,"5.64":5.6,"1.04":1.24,"3.92":3.37,"1065":1265},{"1":1,"14.23":13.82,"1.71":1.75,"2.43":2.42,"15.6":14.0,"127":111,"2.8":3.88,"3.06":3.74,".28":0.32,"2.29":1.87,"5.64":7.05,"1.04":1.01,"3.92":3.26,"1065":1190},{"1":1,"14.23":13.77,"1.71":1.9,"2.43":2.68,"15.6":17.1,"127":115,"2.8":3.0,"3.06":2.79,".28":0.39,"2.29":1.68,"5.64":6.3,"1.04":1.13,"3.92":2.93,"1065":1375},{"1":1,"14.23":13.74,"1.71":1.67,"2.43":2.25,"15.6":16.4,"127":118,"2.8":2.6,"3.06":2.9,".28":0.21,"2.29":1.62,"5.64":5.85,"1.04":0.92,"3.92":3.2,"1065":1060},{"1":1,"14.23":13.56,"1.71":1.73,"2.43":2.46,"15.6":20.5,"127":116,"2.8":2.96,"3.06":2.78,".28":0.2,"2.29":2.45,"5.64":6.25,"1.04":0.98,"3.92":3.03,"1065":1120},{"1":1,"14.23":14.22,"1.71":1.7,"2.43":2.3,"15.6":16.3,"127":118,"2.8":3.2,"3.06":3.0,".28":0.26,"2.29":2.03,"5.64":6.38,"1.04":0.94,"3.92":3.31,"1065":970},{"1":1,"14.23":13.29,"1.71":1.97,"2.43":2.68,"15.6":16.8,"127":102,"2.8":3.0,"3.06":3.23,".28":0.31,"2.29":1.66,"5.64":6.0,"1.04":1.07,"3.92":2.84,"1065":1270},{"1":1,"14.23":13.72,"1.71":1.43,"2.43":2.5,"15.6":16.7,"127":108,"2.8":3.4,"3.06":3.67,".28":0.19,"2.29":2.04,"5.64":6.8,"1.04":0.89,"3.92":2.87,"1065":1285},{"1":2,"14.23":12.37,"1.71":0.94,"2.43":1.36,"15.6":10.6,"127":88,"2.8":1.98,"3.06":0.57,".28":0.28,"2.29":0.42,"5.64":1.95,"1.04":1.05,"3.92":1.82,"1065":520},{"1":2,"14.23":12.33,"1.71":1.1,"2.43":2.28,"15.6":16.0,"127":101,"2.8":2.05,"3.06":1.09,".28":0.63,"2.29":0.41,"5.64":3.27,"1.04":1.25,"3.92":1.67,"1065":680},{"1":2,"14.23":12.64,"1.71":1.36,"2.43":2.02,"15.6":16.8,"127":100,"2.8":2.02,"3.06":1.41,".28":0.53,"2.29":0.62,"5.64":5.75,"1.04":0.98,"3.92":1.59,"1065":450},{"1":2,"14.23":13.67,"1.71":1.25,"2.43":1.92,"15.6":18.0,"127":94,"2.8":2.1,"3.06":1.79,".28":0.32,"2.29":0.73,"5.64":3.8,"1.04":1.23,"3.92":2.46,"1065":630},{"1":2,"14.23":12.37,"1.71":1.13,"2.43":2.16,"15.6":19.0,"127":87,"2.8":3.5,"3.06":3.1,".28":0.19,"2.29":1.87,"5.64":4.45,"1.04":1.22,"3.92":2.87,"1065":420},{"1":2,"14.23":12.17,"1.71":1.45,"2.43":2.53,"15.6":19.0,"127":104,"2.8":1.89,"3.06":1.75,".28":0.45,"2.29":1.03,"5.64":2.95,"1.04":1.45,"3.92":2.23,"1065":355},{"1":2,"14.23":12.37,"1.71":1.21,"2.43":2.56,"15.6":18.1,"127":98,"2.8":2.42,"3.06":2.65,".28":0.37,"2.29":2.08,"5.64":4.6,"1.04":1.19,"3.92":2.3,"1065":678},{"1":2,"14.23":13.11,"1.71":1.01,"2.43":1.7,"15.6":15.0,"127":78,"2.8":2.98,"3.06":3.18,".28":0.26,"2.29":2.28,"5.64":5.3,"1.04":1.12,"3.92":3.18,"1065":502},{"1":2,"14.23":12.37,"1.71":1.17,"2.43":1.92,"15.6":19.6,"127":78,"2.8":2.11,"3.06":2.0,".28":0.27,"2.29":1.04,"5.64":4.68,"1.04":1.12,"3.92":3.48,"1065":510},{"1":2,"14.23":13.34,"1.71":0.94,"2.43":2.36,"15.6":17.0,"127":110,"2.8":2.53,"3.06":1.3,".28":0.55,"2.29":0.42,"5.64":3.17,"1.04":1.02,"3.92":1.93,"1065":750},{"1":2,"14.23":12.21,"1.71":1.19,"2.43":1.75,"15.6":16.8,"127":151,"2.8":1.85,"3.06":1.28,".28":0.14,"2.29":2.5,"5.64":2.85,"1.04":1.28,"3.92":3.07,"1065":718},{"1":2,"14.23":12.29,"1.71":1.61,"2.43":2.21,"15.6":20.4,"127":103,"2.8":1.1,"3.06":1.02,".28":0.37,"2.29":1.46,"5.64":3.05,"1.04":0.906,"3.92":1.82,"1065":870},{"1":2,"14.23":13.86,"1.71":1.51,"2.43":2.67,"15.6":25.0,"127":86,"2.8":2.95,"3.06":2.86,".28":0.21,"2.29":1.87,"5.64":3.38,"1.04":1.36,"3.92":3.16,"1065":410},{"1":2,"14.23":13.49,"1.71":1.66,"2.43":2.24,"15.6":24.0,"127":87,"2.8":1.88,"3.06":1.84,".28":0.27,"2.29":1.03,"5.64":3.74,"1.04":0.98,"3.92":2.78,"1065":472},{"1":2,"14.23":12.99,"1.71":1.67,"2.43":2.6,"15.6":30.0,"127":139,"2.8":3.3,"3.06":2.89,".28":0.21,"2.29":1.96,"5.64":3.35,"1.04":1.31,"3.92":3.5,"1065":985},{"1":2,"14.23":11.96,"1.71":1.09,"2.43":2.3,"15.6":21.0,"127":101,"2.8":3.38,"3.06":2.14,".28":0.13,"2.29":1.65,"5.64":3.21,"1.04":0.99,"3.92":3.13,"1065":886},{"1":2,"14.23":11.66,"1.71":1.88,"2.43":1.92,"15.6":16.0,"127":97,"2.8":1.61,"3.06":1.57,".28":0.34,"2.29":1.15,"5.64":3.8,"1.04":1.23,"3.92":2.14,"1065":428},{"1":2,"14.23":13.03,"1.71":0.9,"2.43":1.71,"15.6":16.0,"127":86,"2.8":1.95,"3.06":2.03,".28":0.24,"2.29":1.46,"5.64":4.6,"1.04":1.19,"3.92":2.48,"1065":392},{"1":2,"14.23":11.84,"1.71":2.89,"2.43":2.23,"15.6":18.0,"127":112,"2.8":1.72,"3.06":1.32,".28":0.43,"2.29":0.95,"5.64":2.65,"1.04":0.96,"3.92":2.52,"1065":500},{"1":2,"14.23":12.33,"1.71":0.99,"2.43":1.95,"15.6":14.8,"127":136,"2.8":1.9,"3.06":1.85,".28":0.35,"2.29":2.76,"5.64":3.4,"1.04":1.06,"3.92":2.31,"1065":750},{"1":2,"14.23":12.7,"1.71":3.87,"2.43":2.4,"15.6":23.0,"127":101,"2.8":2.83,"3.06":2.55,".28":0.43,"2.29":1.95,"5.64":2.57,"1.04":1.19,"3.92":3.13,"1065":463},{"1":2,"14.23":12.0,"1.71":0.92,"2.43":2.0,"15.6":19.0,"127":86,"2.8":2.42,"3.06":2.26,".28":0.3,"2.29":1.43,"5.64":2.5,"1.04":1.38,"3.92":3.12,"1065":278},{"1":2,"14.23":12.72,"1.71":1.81,"2.43":2.2,"15.6":18.8,"127":86,"2.8":2.2,"3.06":2.53,".28":0.26,"2.29":1.77,"5.64":3.9,"1.04":1.16,"3.92":3.14,"1065":714},{"1":2,"14.23":12.08,"1.71":1.13,"2.43":2.51,"15.6":24.0,"127":78,"2.8":2.0,"3.06":1.58,".28":0.4,"2.29":1.4,"5.64":2.2,"1.04":1.31,"3.92":2.72,"1065":630},{"1":2,"14.23":13.05,"1.71":3.86,"2.43":2.32,"15.6":22.5,"127":85,"2.8":1.65,"3.06":1.59,".28":0.61,"2.29":1.62,"5.64":4.8,"1.04":0.84,"3.92":2.01,"1065":515},{"1":2,"14.23":11.84,"1.71":0.89,"2.43":2.58,"15.6":18.0,"127":94,"2.8":2.2,"3.06":2.21,".28":0.22,"2.29":2.35,"5.64":3.05,"1.04":0.79,"3.92":3.08,"1065":520},{"1":2,"14.23":12.67,"1.71":0.98,"2.43":2.24,"15.6":18.0,"127":99,"2.8":2.2,"3.06":1.94,".28":0.3,"2.29":1.46,"5.64":2.62,"1.04":1.23,"3.92":3.16,"1065":450},{"1":2,"14.23":12.16,"1.71":1.61,"2.43":2.31,"15.6":22.8,"127":90,"2.8":1.78,"3.06":1.69,".28":0.43,"2.29":1.56,"5.64":2.45,"1.04":1.33,"3.92":2.26,"1065":495},{"1":2,"14.23":11.65,"1.71":1.67,"2.43":2.62,"15.6":26.0,"127":88,"2.8":1.92,"3.06":1.61,".28":0.4,"2.29":1.34,"5.64":2.6,"1.04":1.36,"3.92":3.21,"1065":562},{"1":2,"14.23":11.64,"1.71":2.06,"2.43":2.46,"15.6":21.6,"127":84,"2.8":1.95,"3.06":1.69,".28":0.48,"2.29":1.35,"5.64":2.8,"1.04":1.0,"3.92":2.75,"1065":680},{"1":2,"14.23":12.08,"1.71":1.33,"2.43":2.3,"15.6":23.6,"127":70,"2.8":2.2,"3.06":1.59,".28":0.42,"2.29":1.38,"5.64":1.74,"1.04":1.07,"3.92":3.21,"1065":625},{"1":2,"14.23":12.08,"1.71":1.83,"2.43":2.32,"15.6":18.5,"127":81,"2.8":1.6,"3.06":1.5,".28":0.52,"2.29":1.64,"5.64":2.4,"1.04":1.08,"3.92":2.27,"1065":480},{"1":2,"14.23":12.0,"1.71":1.51,"2.43":2.42,"15.6":22.0,"127":86,"2.8":1.45,"3.06":1.25,".28":0.5,"2.29":1.63,"5.64":3.6,"1.04":1.05,"3.92":2.65,"1065":450},{"1":2,"14.23":12.69,"1.71":1.53,"2.43":2.26,"15.6":20.7,"127":80,"2.8":1.38,"3.06":1.46,".28":0.58,"2.29":1.62,"5.64":3.05,"1.04":0.96,"3.92":2.06,"1065":495},{"1":2,"14.23":12.29,"1.71":2.83,"2.43":2.22,"15.6":18.0,"127":88,"2.8":2.45,"3.06":2.25,".28":0.25,"2.29":1.99,"5.64":2.15,"1.04":1.15,"3.92":3.3,"1065":290},{"1":2,"14.23":11.62,"1.71":1.99,"2.43":2.28,"15.6":18.0,"127":98,"2.8":3.02,"3.06":2.26,".28":0.17,"2.29":1.35,"5.64":3.25,"1.04":1.16,"3.92":2.96,"1065":345},{"1":2,"14.23":12.47,"1.71":1.52,"2.43":2.2,"15.6":19.0,"127":162,"2.8":2.5,"3.06":2.27,".28":0.32,"2.29":3.28,"5.64":2.6,"1.04":1.16,"3.92":2.63,"1065":937},{"1":2,"14.23":11.81,"1.71":2.12,"2.43":2.74,"15.6":21.5,"127":134,"2.8":1.6,"3.06":0.99,".28":0.14,"2.29":1.56,"5.64":2.5,"1.04":0.95,"3.92":2.26,"1065":625},{"1":2,"14.23":12.29,"1.71":1.41,"2.43":1.98,"15.6":16.0,"127":85,"2.8":2.55,"3.06":2.5,".28":0.29,"2.29":1.77,"5.64":2.9,"1.04":1.23,"3.92":2.74,"1065":428},{"1":2,"14.23":12.37,"1.71":1.07,"2.43":2.1,"15.6":18.5,"127":88,"2.8":3.52,"3.06":3.75,".28":0.24,"2.29":1.95,"5.64":4.5,"1.04":1.04,"3.92":2.77,"1065":660},{"1":2,"14.23":12.29,"1.71":3.17,"2.43":2.21,"15.6":18.0,"127":88,"2.8":2.85,"3.06":2.99,".28":0.45,"2.29":2.81,"5.64":2.3,"1.04":1.42,"3.92":2.83,"1065":406},{"1":2,"14.23":12.08,"1.71":2.08,"2.43":1.7,"15.6":17.5,"127":97,"2.8":2.23,"3.06":2.17,".28":0.26,"2.29":1.4,"5.64":3.3,"1.04":1.27,"3.92":2.96,"1065":710},{"1":2,"14.23":12.6,"1.71":1.34,"2.43":1.9,"15.6":18.5,"127":88,"2.8":1.45,"3.06":1.36,".28":0.29,"2.29":1.35,"5.64":2.45,"1.04":1.04,"3.92":2.77,"1065":562},{"1":2,"14.23":12.34,"1.71":2.45,"2.43":2.46,"15.6":21.0,"127":98,"2.8":2.56,"3.06":2.11,".28":0.34,"2.29":1.31,"5.64":2.8,"1.04":0.8,"3.92":3.38,"1065":438},{"1":2,"14.23":11.82,"1.71":1.72,"2.43":1.88,"15.6":19.5,"127":86,"2.8":2.5,"3.06":1.64,".28":0.37,"2.29":1.42,"5.64":2.06,"1.04":0.94,"3.92":2.44,"1065":415},{"1":2,"14.23":12.51,"1.71":1.73,"2.43":1.98,"15.6":20.5,"127":85,"2.8":2.2,"3.06":1.92,".28":0.32,"2.29":1.48,"5.64":2.94,"1.04":1.04,"3.92":3.57,"1065":672},{"1":2,"14.23":12.42,"1.71":2.55,"2.43":2.27,"15.6":22.0,"127":90,"2.8":1.68,"3.06":1.84,".28":0.66,"2.29":1.42,"5.64":2.7,"1.04":0.86,"3.92":3.3,"1065":315},{"1":2,"14.23":12.25,"1.71":1.73,"2.43":2.12,"15.6":19.0,"127":80,"2.8":1.65,"3.06":2.03,".28":0.37,"2.29":1.63,"5.64":3.4,"1.04":1.0,"3.92":3.17,"1065":510},{"1":2,"14.23":12.72,"1.71":1.75,"2.43":2.28,"15.6":22.5,"127":84,"2.8":1.38,"3.06":1.76,".28":0.48,"2.29":1.63,"5.64":3.3,"1.04":0.88,"3.92":2.42,"1065":488},{"1":2,"14.23":12.22,"1.71":1.29,"2.43":1.94,"15.6":19.0,"127":92,"2.8":2.36,"3.06":2.04,".28":0.39,"2.29":2.08,"5.64":2.7,"1.04":0.86,"3.92":3.02,"1065":312},{"1":2,"14.23":11.61,"1.71":1.35,"2.43":2.7,"15.6":20.0,"127":94,"2.8":2.74,"3.06":2.92,".28":0.29,"2.29":2.49,"5.64":2.65,"1.04":0.96,"3.92":3.26,"1065":680},{"1":2,"14.23":11.46,"1.71":3.74,"2.43":1.82,"15.6":19.5,"127":107,"2.8":3.18,"3.06":2.58,".28":0.24,"2.29":3.58,"5.64":2.9,"1.04":0.75,"3.92":2.81,"1065":562},{"1":2,"14.23":12.52,"1.71":2.43,"2.43":2.17,"15.6":21.0,"127":88,"2.8":2.55,"3.06":2.27,".28":0.26,"2.29":1.22,"5.64":2.0,"1.04":0.9,"3.92":2.78,"1065":325},{"1":2,"14.23":11.76,"1.71":2.68,"2.43":2.92,"15.6":20.0,"127":103,"2.8":1.75,"3.06":2.03,".28":0.6,"2.29":1.05,"5.64":3.8,"1.04":1.23,"3.92":2.5,"1065":607},{"1":2,"14.23":11.41,"1.71":0.74,"2.43":2.5,"15.6":21.0,"127":88,"2.8":2.48,"3.06":2.01,".28":0.42,"2.29":1.44,"5.64":3.08,"1.04":1.1,"3.92":2.31,"1065":434},{"1":2,"14.23":12.08,"1.71":1.39,"2.43":2.5,"15.6":22.5,"127":84,"2.8":2.56,"3.06":2.29,".28":0.43,"2.29":1.04,"5.64":2.9,"1.04":0.93,"3.92":3.19,"1065":385},{"1":2,"14.23":11.03,"1.71":1.51,"2.43":2.2,"15.6":21.5,"127":85,"2.8":2.46,"3.06":2.17,".28":0.52,"2.29":2.01,"5.64":1.9,"1.04":1.71,"3.92":2.87,"1065":407},{"1":2,"14.23":11.82,"1.71":1.47,"2.43":1.99,"15.6":20.8,"127":86,"2.8":1.98,"3.06":1.6,".28":0.3,"2.29":1.53,"5.64":1.95,"1.04":0.95,"3.92":3.33,"1065":495},{"1":2,"14.23":12.42,"1.71":1.61,"2.43":2.19,"15.6":22.5,"127":108,"2.8":2.0,"3.06":2.09,".28":0.34,"2.29":1.61,"5.64":2.06,"1.04":1.06,"3.92":2.96,"1065":345},{"1":2,"14.23":12.77,"1.71":3.43,"2.43":1.98,"15.6":16.0,"127":80,"2.8":1.63,"3.06":1.25,".28":0.43,"2.29":0.83,"5.64":3.4,"1.04":0.7,"3.92":2.12,"1065":372},{"1":2,"14.23":12.0,"1.71":3.43,"2.43":2.0,"15.6":19.0,"127":87,"2.8":2.0,"3.06":1.64,".28":0.37,"2.29":1.87,"5.64":1.28,"1.04":0.93,"3.92":3.05,"1065":564},{"1":2,"14.23":11.45,"1.71":2.4,"2.43":2.42,"15.6":20.0,"127":96,"2.8":2.9,"3.06":2.79,".28":0.32,"2.29":1.83,"5.64":3.25,"1.04":0.8,"3.92":3.39,"1065":625},{"1":2,"14.23":11.56,"1.71":2.05,"2.43":3.23,"15.6":28.5,"127":119,"2.8":3.18,"3.06":5.08,".28":0.47,"2.29":1.87,"5.64":6.0,"1.04":0.93,"3.92":3.69,"1065":465},{"1":2,"14.23":12.42,"1.71":4.43,"2.43":2.73,"15.6":26.5,"127":102,"2.8":2.2,"3.06":2.13,".28":0.43,"2.29":1.71,"5.64":2.08,"1.04":0.92,"3.92":3.12,"1065":365},{"1":2,"14.23":13.05,"1.71":5.8,"2.43":2.13,"15.6":21.5,"127":86,"2.8":2.62,"3.06":2.65,".28":0.3,"2.29":2.01,"5.64":2.6,"1.04":0.73,"3.92":3.1,"1065":380},{"1":2,"14.23":11.87,"1.71":4.31,"2.43":2.39,"15.6":21.0,"127":82,"2.8":2.86,"3.06":3.03,".28":0.21,"2.29":2.91,"5.64":2.8,"1.04":0.75,"3.92":3.64,"1065":380},{"1":2,"14.23":12.07,"1.71":2.16,"2.43":2.17,"15.6":21.0,"127":85,"2.8":2.6,"3.06":2.65,".28":0.37,"2.29":1.35,"5.64":2.76,"1.04":0.86,"3.92":3.28,"1065":378},{"1":2,"14.23":12.43,"1.71":1.53,"2.43":2.29,"15.6":21.5,"127":86,"2.8":2.74,"3.06":3.15,".28":0.39,"2.29":1.77,"5.64":

In [24]:
url='https://www.fdic.gov/bank/individual/failed/banklist.html'

In [26]:
df=pd.read_html(url)

In [27]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524